version: '3.8'

services:
  timestamp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: timestamp-server:latest
    container_name: timestamp-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./keystores:/app/keystores
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3