spring:
  application:
    name: timestamp-server
  jackson:
    serialization:
      indent-output: true

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# TSA Configuration
tsa:
  policy: "1.3.6.1.4.1.13762.3"
  accuracy:
    seconds: 1
    millis: 0
    micros: 0
  certificates:
    keystore:
      path: classpath:keystore.jks
      password: changeit
      alias: tsa
  serialNumberLength: 64

logging:
  level:
    root: INFO
    com.albaraka.tsa.timestampserver: DEBUG
    org.springframework.web: INFO